### ISSUE TITLE
Program does not terminate during generation

### ISSUE THREAD

**Issue by fangyi-zhou** [MislankaNova/geo#4]
In a POSIX OS, SDL will capture the termination signals at initialisation. The signal will generate an `SDL_QUIT` event instead of terminating the program directly.
(Reference https://wiki.libsdl.org/SDL_EventType#Remarks)

Hence during generation, the events are not handled as generation work is occupying CPU. This leads to termination signals not being handled promptly and program keeps running.

**Comment by fangyi-zhou** [comment]
#3 was an attempt to fix this issue, but does not address the problem in full. See also discussion in the PR.

**Comment by MislankaNova** [comment]
As I said ealier, the current `main` function is not well-organised and some serious refactoring/rewritting would be needed, not only to solve this specific problem but to improve the clarity in general and to allow easier addition of functionalities.

My current idea is to initialise SDL and create the window only after the generation is finished, so SDL would not get in our way when the terrain is still been generated. I may need to read the the parts of the SDL documentation regarding SDL context and window creation more thoroughly before making any change. Please let me know if you have any suggestions on this.

**Comment by MislankaNova** [comment]
The handler for `SDL_QUIT` event have been added in caac1f5a5be45bf12328ffe4c97e639effb935ba. I will be working on the restructuring of `main` once I become once again able to allocate some of my time for _geo_.

(Notice that a graphic driver bug is preventing `SIGINT` from being properly handled on certain machines, see https://stackoverflow.com/questions/20049025/cant-ctrl-c-my-sdl-apps-anymore.)
